[package]
name = "quantum_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
nalgebra = "0.32.5"
num-traits = "0.2.18"
